// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADplagtwTyd7rhTP9ucZLKHYJJwLF2WfM',
    appId: '1:533572830982:web:6ab36467588db2d970c087',
    messagingSenderId: '533572830982',
    projectId: 'ecommerceapp-d2277',
    authDomain: 'ecommerceapp-d2277.firebaseapp.com',
    storageBucket: 'ecommerceapp-d2277.firebasestorage.app',
    measurementId: 'G-20NTGV70SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1WX793i6_iorPqMVOSDEkfSQBbay70Iw',
    appId: '1:533572830982:android:2c170ae9e085387570c087',
    messagingSenderId: '533572830982',
    projectId: 'ecommerceapp-d2277',
    storageBucket: 'ecommerceapp-d2277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYyOgCtiv_PoWzaOK4QmkPEjzmslTUe50',
    appId: '1:533572830982:ios:61f7cba8b4c25dbf70c087',
    messagingSenderId: '533572830982',
    projectId: 'ecommerceapp-d2277',
    storageBucket: 'ecommerceapp-d2277.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADplagtwTyd7rhTP9ucZLKHYJJwLF2WfM',
    appId: '1:533572830982:web:bda6b074e53929ea70c087',
    messagingSenderId: '533572830982',
    projectId: 'ecommerceapp-d2277',
    authDomain: 'ecommerceapp-d2277.firebaseapp.com',
    storageBucket: 'ecommerceapp-d2277.firebasestorage.app',
    measurementId: 'G-LWBPCH0ZDZ',
  );
}
