name: iOS Unsigned Build

on:
  push:
    branches:
      - main # main dalına kod pushlandığında çalışır

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Bağımlılıkları Yükle
        run: flutter pub get

      - name: İmzasız iOS Derlemesi Al
        run: flutter build ios --release --no-codesign

      - name: Çıktıyı .ipa Formatına Dönüştür
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r -q app.ipa Payload

      - name: .ipa Dosyasını İndirmeye Hazırla
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-unsigned
          path: app.ipa
